"""Auto-generated by scripts/gen_prompt_constants.py — do not edit."""

class PromptId:
    """Constants for every prompt in codeograph/prompts/."""
    ANNOTATE_NODE = "annotate_node"
    SYNTHESIZE_CORPUS = "synthesize_corpus"
