#!/usr/bin/env python3
from pathlib import Path


def main():
    base_dir = Path(__file__).parent.parent / "codeograph" / "prompts"
    out_file = Path(__file__).parent.parent / "codeograph" / "llm" / "_prompts_generated.py"

    if not base_dir.exists():
        base_dir.mkdir(parents=True, exist_ok=True)

    prompt_ids = []
    for d in base_dir.iterdir():
        if d.is_dir():
            prompt_ids.append(d.name)

    prompt_ids.sort()

    # Layout matches `ruff format` output so the CI freshness gate is stable:
    # PEP 8 requires two blank lines before a top-level class, and a blank line
    # after the class docstring before the first statement.
    lines = [
        '"""Auto-generated by scripts/gen_prompt_constants.py — do not edit."""',
        "",
        "",
        "class PromptId:",
        '    """Constants for every prompt in codeograph/prompts/."""',
        "",
    ]

    for pid in prompt_ids:
        const_name = pid.upper().replace("-", "_")
        lines.append(f'    {const_name} = "{pid}"')

    if not prompt_ids:
        lines.append("    pass")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
