# generated by datamodel-codegen:
#   filename:  graph.schema.json
#   timestamp: 2026-05-05T14:46:57+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ModuleNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: mod:<module-name>. e.g. mod:module-core',
            pattern='^mod:.+',
        ),
    ]
    kind: Literal['module']


class ClassNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(description='Fully-qualified class name. e.g. com.example.UserService'),
    ]
    kind: Literal['class']


class InterfaceNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified interface name.')]
    kind: Literal['interface']


class EnumNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified enum name.')]
    kind: Literal['enum']


class RecordNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified record name.')]
    kind: Literal['record']


class AnnotationTypeNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified annotation type name.')]
    kind: Literal['annotation_type']


class MethodNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: <fqcn>#<method>(<param-types>). e.g. com.example.UserService#findById(Long)'
        ),
    ]
    kind: Literal['method']


class FieldNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: <fqcn>.<field-name>. e.g. com.example.UserService.userRepository'
        ),
    ]
    kind: Literal['field']


class ContainsEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[
        str, Field(description='ID of the containing node (module, class).')
    ]
    target: Annotated[
        str, Field(description='ID of the contained node (class, method, field).')
    ]
    kind: Literal['contains']


class CallsResolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Calling method ID.')]
    target: Annotated[
        str, Field(description='Called method ID — resolved to a known node.')
    ]
    kind: Literal['calls_resolved']


class CallsUnresolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Calling method ID.')]
    target: Annotated[
        str,
        Field(
            description='Best-effort callee name. May not match any node ID in the graph.'
        ),
    ]
    kind: Literal['calls_unresolved']


class DependsOnEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Depending class ID.')]
    target: Annotated[str, Field(description='Depended-upon class ID.')]
    kind: Literal['depends_on']


class AutowiresEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[
        str, Field(description='Field ID carrying the injection annotation.')
    ]
    target: Annotated[str, Field(description='Injected class ID.')]
    kind: Literal['autowires']


class Node(
    RootModel[
        ModuleNode
        | ClassNode
        | InterfaceNode
        | EnumNode
        | RecordNode
        | AnnotationTypeNode
        | MethodNode
        | FieldNode
    ]
):
    root: (
        ModuleNode
        | ClassNode
        | InterfaceNode
        | EnumNode
        | RecordNode
        | AnnotationTypeNode
        | MethodNode
        | FieldNode
    )


class Edge(
    RootModel[
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
    ]
):
    root: (
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
    )


class CodeographKnowledgeGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodes: Annotated[
        list[Node],
        Field(description="All graph nodes. Discriminated by the 'kind' property."),
    ]
    edges: Annotated[
        list[Edge],
        Field(description="All graph edges. Discriminated by the 'kind' property."),
    ]
