# generated by datamodel-codegen:
#   filename:  graph.schema.json
#   timestamp: 2026-05-06T13:53:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BuildTool(Enum):
    maven = 'maven'
    gradle = 'gradle'


class ModuleNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: mod:<module-name>. e.g. mod:module-core',
            pattern='^mod:.+',
        ),
    ]
    kind: Literal['module']
    name: Annotated[str, Field(description='Maven artifactId of this module.')]
    build_tool: Annotated[
        BuildTool, Field(description='Build system detected for this module (ADR-002).')
    ]
    source_roots: Annotated[
        list[str],
        Field(
            description='Source root paths. See source_file DECISION below for what these are relative to.'
        ),
    ]
    pom_path: Annotated[
        str | None, Field(description='Path to pom.xml. Null for Gradle modules in v1.')
    ] = None


class Modifier(Enum):
    public = 'public'
    protected = 'protected'
    private = 'private'
    abstract = 'abstract'
    final = 'final'
    static = 'static'


class Stereotype(Enum):
    field_Service = '@Service'
    field_Repository = '@Repository'
    field_Controller = '@Controller'
    field_RestController = '@RestController'
    field_Component = '@Component'
    field_Configuration = '@Configuration'
    field_Entity = '@Entity'
    field_Aspect = '@Aspect'
    NoneType_None = None


class ClassNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(description='Fully-qualified class name. e.g. com.example.UserService'),
    ]
    kind: Literal['class']
    name: Annotated[str, Field(description='Simple class name. e.g. UserService')]
    modifiers: Annotated[
        list[Modifier],
        Field(
            description='Java access and non-access modifiers declared on this class.'
        ),
    ]
    stereotype: Annotated[
        Stereotype | None,
        Field(
            description='Primary Spring stereotype annotation, if any. DECISION-1: confirm this list.'
        ),
    ] = None
    superclass: Annotated[
        str | None,
        Field(
            description='FQCN of the superclass, or null if extends Object implicitly.'
        ),
    ] = None
    implements: Annotated[
        list[str] | None, Field(description='FQCNs of implemented interfaces.')
    ] = None
    is_inner_class: Annotated[
        bool | None,
        Field(description='True if this class is declared inside another class.'),
    ] = None
    source_file: Annotated[
        str, Field(description='DECISION-2 (see below): path to the .java source file.')
    ]
    line_range: Annotated[
        list[int],
        Field(
            description='[start_line, end_line] of the class declaration.',
            max_length=2,
            min_length=2,
        ),
    ]
    wmc: Annotated[
        int | None,
        Field(
            description='Weighted Method Count — sum of cyclomatic complexities of all methods (ADR-004, Chidamber & Kemerer 1994). Deterministic; lives here not in llm-annotations.'
        ),
    ] = None
    cbo: Annotated[
        int | None,
        Field(
            description='Coupling Between Objects — count of distinct classes this class depends on (ADR-004, Chidamber & Kemerer 1994).'
        ),
    ] = None
    lcom4: Annotated[
        int | None,
        Field(
            description='Lack of Cohesion of Methods 4 — number of connected components in the method-field usage graph (ADR-004, Hitz & Montazeri 1995).'
        ),
    ] = None


class Modifier1(Enum):
    public = 'public'
    protected = 'protected'
    private = 'private'
    abstract = 'abstract'
    static = 'static'


class InterfaceNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified interface name.')]
    kind: Literal['interface']
    name: str
    modifiers: list[Modifier1]
    extends_interfaces: Annotated[
        list[str] | None, Field(description='FQCNs of extended interfaces.')
    ] = None
    source_file: Annotated[str, Field(description='DECISION-2 (see below).')]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class Modifier2(Enum):
    public = 'public'
    protected = 'protected'
    private = 'private'


class EnumNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified enum name.')]
    kind: Literal['enum']
    name: str
    modifiers: list[Modifier2]
    constants: Annotated[
        list[str], Field(description='Enum constant names in declaration order.')
    ]
    implements: Annotated[
        list[str] | None, Field(description='FQCNs of implemented interfaces.')
    ] = None
    source_file: Annotated[str, Field(description='DECISION-2 (see below).')]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class Modifier4(Enum):
    public = 'public'
    protected = 'protected'
    private = 'private'
    abstract = 'abstract'
    final = 'final'
    static = 'static'
    synchronized = 'synchronized'
    native = 'native'


class ExtractionMode(Enum):
    full = 'full'
    signatures_only = 'signatures_only'


class Modifier5(Enum):
    public = 'public'
    protected = 'protected'
    private = 'private'
    final = 'final'
    static = 'static'
    transient = 'transient'
    volatile = 'volatile'


class FieldNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: <fqcn>.<field-name>. e.g. com.example.UserService.userRepository'
        ),
    ]
    kind: Literal['field']
    name: str
    type: Annotated[
        str,
        Field(
            description='Declared field type as a string. e.g. UserRepository, List<Order>, String.'
        ),
    ]
    modifiers: list[Modifier5]
    annotations: Annotated[
        list[str] | None,
        Field(
            description='Annotation simple names on this field. e.g. ["Autowired", "NotNull"].'
        ),
    ] = None
    is_autowired: Annotated[
        bool | None,
        Field(
            description='DECISION-4: convenience flag — true if this field carries @Autowired, @Inject, or equivalent. Redundant with the AUTOWIRES edge but simplifies renderer queries.'
        ),
    ] = None


class ContainsEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='ID of the containing node.')]
    target: Annotated[str, Field(description='ID of the contained node.')]
    kind: Literal['contains']


class CallsResolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Calling method ID.')]
    target: Annotated[
        str, Field(description='Called method ID — resolved to a known node.')
    ]
    kind: Literal['calls_resolved']
    call_count: Annotated[
        int | None,
        Field(
            description='How many times this method calls the target within its body.'
        ),
    ] = None


class CallsUnresolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Calling method ID.')]
    target: Annotated[
        str, Field(description='Best-effort callee name. May not match any node ID.')
    ]
    kind: Literal['calls_unresolved']
    raw_call_expr: Annotated[
        str | None,
        Field(
            description='The literal call expression from source, for debuggability. e.g. orderService.findByUser(userId)'
        ),
    ] = None


class DependsOnEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(description='Depending class ID.')]
    target: Annotated[str, Field(description='Depended-upon class ID.')]
    kind: Literal['depends_on']


class InjectionType(Enum):
    field = 'field'
    constructor = 'constructor'
    setter = 'setter'


class AutowiresEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[
        str, Field(description='Field ID carrying the injection annotation.')
    ]
    target: Annotated[str, Field(description='Injected class ID.')]
    kind: Literal['autowires']
    injection_type: Annotated[
        InjectionType | None,
        Field(
            description='DECISION-5: how the dependency is injected. Drives renderer output.'
        ),
    ] = None


class NameTypePair(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: Annotated[
        str,
        Field(description='Type as a string. e.g. Long, List<Order>, UserRepository.'),
    ]


class AnnotationElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: str
    default_value: Annotated[
        str | None,
        Field(
            description='String representation of the default value, or null if no default.'
        ),
    ] = None


class RecordNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified record name.')]
    kind: Literal['record']
    name: str
    components: Annotated[
        list[NameTypePair], Field(description='Record components in declaration order.')
    ]
    implements: Annotated[
        list[str] | None, Field(description='FQCNs of implemented interfaces.')
    ] = None
    source_file: Annotated[str, Field(description='DECISION-2 (see below).')]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class AnnotationTypeNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Fully-qualified annotation type name.')]
    kind: Literal['annotation_type']
    name: str
    modifiers: list[Modifier2]
    elements: Annotated[
        list[AnnotationElement] | None,
        Field(description='Annotation element declarations.'),
    ] = None
    source_file: Annotated[str, Field(description='DECISION-2 (see below).')]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class MethodNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='Format: <fqcn>#<method>(<param-types>). e.g. com.example.UserService#findById(Long)'
        ),
    ]
    kind: Literal['method']
    name: Annotated[
        str,
        Field(
            description='Method name. For constructors, matches the class simple name.'
        ),
    ]
    return_type: Annotated[
        str,
        Field(
            description="Return type as a string. 'void' for void methods. Constructor return_type is the class FQCN."
        ),
    ]
    parameters: Annotated[
        list[NameTypePair], Field(description='Method parameters in declaration order.')
    ]
    modifiers: list[Modifier4]
    annotations: Annotated[
        list[str] | None,
        Field(
            description='Annotation simple names present on this method. e.g. ["Override", "GetMapping"].'
        ),
    ] = None
    is_constructor: bool
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]
    cyclomatic_complexity: Annotated[
        int | None,
        Field(
            description='McCabe cyclomatic complexity (ADR-004). Null if extraction_mode is signatures_only.'
        ),
    ] = None
    cognitive_complexity: Annotated[
        int | None,
        Field(
            description='SonarSource cognitive complexity (ADR-004, Campbell 2018). Null if extraction_mode is signatures_only.'
        ),
    ] = None
    method_loc: Annotated[
        int | None,
        Field(
            description='Method lines of code excluding blank lines and comments (ADR-004). Null if extraction_mode is signatures_only.'
        ),
    ] = None
    extraction_mode: Annotated[
        ExtractionMode | None,
        Field(
            description="DECISION-3: include this field? If yes, 'full' means all complexity metrics are present; 'signatures_only' means metrics are null (ADR-005 oversized-input fallback)."
        ),
    ] = None


class Edge(
    RootModel[
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
    ]
):
    root: (
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
    )


class Node(
    RootModel[
        ModuleNode
        | ClassNode
        | InterfaceNode
        | EnumNode
        | RecordNode
        | AnnotationTypeNode
        | MethodNode
        | FieldNode
    ]
):
    root: (
        ModuleNode
        | ClassNode
        | InterfaceNode
        | EnumNode
        | RecordNode
        | AnnotationTypeNode
        | MethodNode
        | FieldNode
    )


class CodeographKnowledgeGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodes: Annotated[
        list[Node],
        Field(description="All graph nodes. Discriminated by the 'kind' property."),
    ]
    edges: Annotated[
        list[Edge],
        Field(description="All graph edges. Discriminated by the 'kind' property."),
    ]
