# generated by datamodel-codegen:
#   filename:  graph.schema.json
#   timestamp: 2026-05-06T17:09:08+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BuildTool(StrEnum):
    maven = "maven"
    gradle = "gradle"


class ModuleNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str,
        Field(
            description="Format: mod:<module-name>. e.g. mod:module-core",
            pattern="^mod:.+",
        ),
    ]
    kind: Literal["module"]
    name: Annotated[str, Field(description="Maven artifactId of this module.")]
    build_tool: Annotated[BuildTool, Field(description="Build system detected for this module (ADR-002).")]
    source_roots: Annotated[
        list[str],
        Field(
            description="Source root paths relative to the repository root. e.g. ['module-core/src/main/java']. Same convention as source_file on class/interface/etc. nodes (DECISION-2 resolved)."
        ),
    ]
    pom_path: Annotated[
        str | None,
        Field(description="Path to pom.xml relative to repository root. Null for Gradle modules in v1."),
    ] = None


class Modifier(StrEnum):
    public = "public"
    protected = "protected"
    private = "private"
    abstract = "abstract"
    final = "final"
    static = "static"


class Stereotype(Enum):
    Component = "Component"
    Service = "Service"
    Repository = "Repository"
    Controller = "Controller"
    RestController = "RestController"
    Configuration = "Configuration"
    ControllerAdvice = "ControllerAdvice"
    Entity = "Entity"
    SpringBootApplication = "SpringBootApplication"
    NoneType_None = None


class ExtractionMode(StrEnum):
    ast = "ast"
    signatures_only = "signatures_only"
    regex_fallback = "regex_fallback"


class ClassNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str,
        Field(description="Fully-qualified class name. e.g. com.example.UserService"),
    ]
    kind: Literal["class"]
    name: Annotated[str, Field(description="Simple class name. e.g. UserService")]
    modifiers: Annotated[
        list[Modifier],
        Field(description="Java access and non-access modifiers declared on this class."),
    ]
    stereotype: Annotated[
        Stereotype | None,
        Field(
            description="Primary Spring stereotype (ADR-003 §9, DECISION-1 resolved). Short name, no @ prefix. Null if no stereotype annotation is present."
        ),
    ] = None
    annotations: Annotated[
        list[str] | None,
        Field(
            description='ALL annotation simple names present on this class, including those not in the interpreted list. e.g. ["Service", "Transactional", "Validated"]. Superset of stereotype.'
        ),
    ] = None
    superclass: Annotated[
        str | None,
        Field(description="FQCN of the superclass, or null if extends Object implicitly."),
    ] = None
    implements: Annotated[list[str] | None, Field(description="FQCNs of implemented interfaces.")] = None
    is_inner_class: Annotated[
        bool | None,
        Field(description="True if this class is declared inside another class."),
    ] = None
    source_file: Annotated[
        str,
        Field(
            description="Path to the .java source file, relative to the repository root. e.g. 'module-core/src/main/java/com/example/UserService.java'. Never absolute — absolute paths break sha256 reproducibility across machines (DECISION-2 resolved)."
        ),
    ]
    line_range: Annotated[
        list[int],
        Field(
            description="[start_line, end_line] of the class declaration.",
            max_length=2,
            min_length=2,
        ),
    ]
    extraction_mode: Annotated[
        ExtractionMode,
        Field(
            description="How this class's body was parsed. 'ast': full JavaParser AST (complexity metrics available). 'signatures_only': oversized-input fallback per ADR-005 (complexity metrics null). 'regex_fallback': JavaParser failed; per-file regex used (ADR-003). Applies to all methods in this class."
        ),
    ]
    table_name: Annotated[
        str | None,
        Field(
            description="Database table name from @Table(name=...) or @Entity default (simple class name lowercased). Null if class is not an @Entity."
        ),
    ] = None
    entry_point: Annotated[
        bool | None,
        Field(
            description="True if this class carries @SpringBootApplication — marks the application bootstrap entry point."
        ),
    ] = None
    wmc: Annotated[
        int | None,
        Field(
            description="Weighted Method Count — sum of cyclomatic complexities of all methods (ADR-004, Chidamber & Kemerer 1994). Null when extraction_mode is 'signatures_only' or 'regex_fallback'."
        ),
    ] = None
    cbo: Annotated[
        int | None,
        Field(
            description="Coupling Between Objects — count of distinct classes this class depends on (ADR-004, Chidamber & Kemerer 1994). Null when extraction_mode is 'signatures_only' or 'regex_fallback'."
        ),
    ] = None
    lcom4: Annotated[
        int | None,
        Field(
            description="Lack of Cohesion of Methods 4 — number of connected components in the method-field usage graph (ADR-004, Hitz & Montazeri 1995). Null when extraction_mode is 'signatures_only' or 'regex_fallback'."
        ),
    ] = None


class Modifier1(StrEnum):
    public = "public"
    protected = "protected"
    private = "private"
    abstract = "abstract"
    static = "static"


class InterfaceNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Fully-qualified interface name.")]
    kind: Literal["interface"]
    name: str
    modifiers: list[Modifier1]
    annotations: Annotated[
        list[str] | None,
        Field(description="Annotation simple names on this interface."),
    ] = None
    extends_interfaces: Annotated[list[str] | None, Field(description="FQCNs of extended interfaces.")] = None
    source_file: Annotated[
        str,
        Field(description="Path relative to the repository root (DECISION-2 resolved)."),
    ]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class Modifier2(StrEnum):
    public = "public"
    protected = "protected"
    private = "private"


class EnumNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Fully-qualified enum name.")]
    kind: Literal["enum"]
    name: str
    modifiers: list[Modifier2]
    constants: Annotated[list[str], Field(description="Enum constant names in declaration order.")]
    annotations: Annotated[list[str] | None, Field(description="Annotation simple names on this enum.")] = None
    implements: Annotated[list[str] | None, Field(description="FQCNs of implemented interfaces.")] = None
    source_file: Annotated[
        str,
        Field(description="Path relative to the repository root (DECISION-2 resolved)."),
    ]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class Modifier4(StrEnum):
    public = "public"
    protected = "protected"
    private = "private"
    abstract = "abstract"
    final = "final"
    static = "static"
    synchronized = "synchronized"
    native = "native"


class Modifier5(StrEnum):
    public = "public"
    protected = "protected"
    private = "private"
    final = "final"
    static = "static"
    transient = "transient"
    volatile = "volatile"


class Generation(Enum):
    AUTO = "AUTO"
    IDENTITY = "IDENTITY"
    SEQUENCE = "SEQUENCE"
    TABLE = "TABLE"
    UUID = "UUID"
    NoneType_None = None


class ContainsEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[
        str,
        Field(description="ID of the containing node (module, class, interface, etc.)."),
    ]
    target: Annotated[str, Field(description="ID of the contained node.")]
    kind: Literal["contains"]


class CallsResolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[str, Field(description="Calling method ID.")]
    target: Annotated[
        str,
        Field(description="Called method ID — resolved to a known node in this graph."),
    ]
    kind: Literal["calls_resolved"]
    call_count: Annotated[
        int | None,
        Field(description="How many times this method calls the target within its body."),
    ] = None


class CallsUnresolvedEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[str, Field(description="Calling method ID.")]
    target: Annotated[
        str,
        Field(
            description="Best-effort callee name. May not match any node ID — could be an external library or JDK method."
        ),
    ]
    kind: Literal["calls_unresolved"]
    raw_call_expr: Annotated[
        str | None,
        Field(
            description="The literal call expression from source, for debuggability. e.g. orderService.findByUser(userId)"
        ),
    ] = None


class DependsOnEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[str, Field(description="Depending class ID.")]
    target: Annotated[
        str,
        Field(description="Depended-upon class ID. Feeds CBO computation for the source class."),
    ]
    kind: Literal["depends_on"]


class InjectionType(StrEnum):
    field = "field"
    constructor = "constructor"
    setter = "setter"


class AutowiresEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[
        str,
        Field(description="Field ID carrying the injection annotation (e.g. com.example.UserService.userRepository)."),
    ]
    target: Annotated[str, Field(description="Injected class/interface FQCN.")]
    kind: Literal["autowires"]
    injection_type: Annotated[
        InjectionType | None,
        Field(
            description="How the dependency is injected (DECISION-5 resolved: fallback is 'field'). Drives renderer output — Go has no field injection; NestJS prefers constructor. Emit 'field' when JavaParser cannot determine injection style."
        ),
    ] = None
    qualifier: Annotated[
        str | None,
        Field(
            description="Value from @Qualifier(value=...) on this injection point, or null if no qualifier. Needed when multiple beans of the same type exist."
        ),
    ] = None


class Cardinality(StrEnum):
    ONE_TO_ONE = "ONE_TO_ONE"
    ONE_TO_MANY = "ONE_TO_MANY"
    MANY_TO_ONE = "MANY_TO_ONE"
    MANY_TO_MANY = "MANY_TO_MANY"


class RelationEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[str, Field(description="Owning class ID (FQCN).")]
    target: Annotated[
        str,
        Field(
            description="Related class ID (FQCN). Extracted from the annotation's targetEntity or the field generic type."
        ),
    ]
    kind: Literal["relation"]
    cardinality: Annotated[
        Cardinality,
        Field(description="JPA relationship cardinality from the annotation name."),
    ]
    join_column: Annotated[
        str | None,
        Field(
            description="Column name from @JoinColumn(name=...), or null if not specified (JPA uses default naming)."
        ),
    ] = None


class BeanFactoryEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[str, Field(description="Method ID of the @Bean factory method.")]
    target: Annotated[str, Field(description="FQCN of the produced bean (the method's return type).")]
    kind: Literal["bean_factory"]


class Method(StrEnum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    PATCH = "PATCH"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"


class HttpMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Annotated[
        Method,
        Field(
            description="HTTP method. Inferred from annotation name (@GetMapping → GET) or from RequestMethod enum in @RequestMapping."
        ),
    ]
    path: Annotated[
        str,
        Field(
            description="URL path template. Combines class-level and method-level mappings. e.g. '/users/{id}'. Empty string if no path is specified."
        ),
    ]


class Kind(StrEnum):
    path = "path"
    query = "query"
    body = "body"
    header = "header"
    request_param = "request_param"
    model_attribute = "model_attribute"


class ParameterBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[
        Kind,
        Field(
            description="Binding source. 'path' = @PathVariable, 'query'/'request_param' = @RequestParam, 'body' = @RequestBody, 'header' = @RequestHeader, 'model_attribute' = @ModelAttribute."
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Explicit binding name from annotation value attribute, or null if not specified (uses parameter name)."
        ),
    ] = None
    required: Annotated[
        bool | None,
        Field(
            description="True if the binding is required (annotation's required attribute, defaults to true for most Spring annotations)."
        ),
    ] = None
    default_value: Annotated[
        str | None,
        Field(description="defaultValue from @RequestParam or @RequestHeader, or null if not specified."),
    ] = None


class ColumnMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description="Column name from name attribute, or null if not specified (JPA uses field name by default)."
        ),
    ] = None
    nullable: Annotated[
        bool | None,
        Field(description="From nullable attribute. Defaults to true per JPA spec."),
    ] = None
    length: Annotated[
        int | None,
        Field(
            description="From length attribute. Applies to VARCHAR columns. Null if not specified (JPA default is 255)."
        ),
    ] = None


class NameTypePair(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Annotated[
        str,
        Field(description="Type as a string. e.g. Long, List<Order>, UserRepository."),
    ]


class AnnotationElement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: str
    default_value: Annotated[
        str | None,
        Field(description="String representation of the default value, or null if no default."),
    ] = None


class RecordNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Fully-qualified record name.")]
    kind: Literal["record"]
    name: str
    components: Annotated[list[NameTypePair], Field(description="Record components in declaration order.")]
    annotations: Annotated[list[str] | None, Field(description="Annotation simple names on this record.")] = None
    implements: Annotated[list[str] | None, Field(description="FQCNs of implemented interfaces.")] = None
    source_file: Annotated[
        str,
        Field(description="Path relative to the repository root (DECISION-2 resolved)."),
    ]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class AnnotationTypeNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="Fully-qualified annotation type name.")]
    kind: Literal["annotation_type"]
    name: str
    modifiers: list[Modifier2]
    elements: Annotated[
        list[AnnotationElement] | None,
        Field(description="Annotation element declarations."),
    ] = None
    source_file: Annotated[
        str,
        Field(description="Path relative to the repository root (DECISION-2 resolved)."),
    ]
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]


class FieldNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str,
        Field(description="Format: <fqcn>.<field-name>. e.g. com.example.UserService.userRepository"),
    ]
    kind: Literal["field"]
    name: str
    type: Annotated[
        str,
        Field(description="Declared field type as a string. e.g. UserRepository, List<Order>, String."),
    ]
    modifiers: list[Modifier5]
    annotations: Annotated[
        list[str] | None,
        Field(description='ALL annotation simple names on this field. e.g. ["Autowired", "NotNull", "Column"].'),
    ] = None
    is_autowired: Annotated[
        bool | None,
        Field(
            description="True if this field carries @Autowired, @Inject, or equivalent (DECISION-4 resolved: include). Redundant with the AutowiresEdge but simplifies renderer queries without edge traversal."
        ),
    ] = None
    is_id: Annotated[
        bool | None,
        Field(description="True if this field carries @Id (ADR-003 §9 — JPA core category). Primary key field."),
    ] = None
    generation: Annotated[
        Generation | None,
        Field(
            description="GenerationType from @GeneratedValue(strategy=...), or null if @GeneratedValue is absent or field is not @Id."
        ),
    ] = None
    column: Annotated[
        ColumnMetadata | None,
        Field(description="Column mapping from @Column, if present. Null/absent if no @Column annotation."),
    ] = None
    constraints: Annotated[
        list[str] | None,
        Field(
            description='Bean Validation constraint annotation simple names on this field (ADR-003 §9 — basic validation category). e.g. ["NotNull", "Size", "Email"]. Does not include JPA or Spring annotations — those have dedicated fields.'
        ),
    ] = None


class Edge(
    RootModel[
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
        | RelationEdge
        | BeanFactoryEdge
    ]
):
    root: (
        ContainsEdge
        | CallsResolvedEdge
        | CallsUnresolvedEdge
        | DependsOnEdge
        | AutowiresEdge
        | RelationEdge
        | BeanFactoryEdge
    )


class ParameterFact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(description="Parameter name as declared in source.")]
    type: Annotated[
        str,
        Field(description="Parameter type as a string. e.g. Long, UserDTO, HttpServletRequest."),
    ]
    binding: Annotated[
        ParameterBinding | None,
        Field(
            description="Spring binding metadata if a binding annotation is present (@PathVariable, @RequestParam, @RequestBody, @RequestHeader, @ModelAttribute). Absent if no binding annotation."
        ),
    ] = None
    validate_: Annotated[
        bool | None,
        Field(
            alias="validate",
            description="True if @Valid or @Validated is present on this parameter.",
        ),
    ] = None
    constraints: Annotated[
        list[str] | None,
        Field(
            description='Bean Validation constraint annotation simple names applied directly to this parameter. e.g. ["NotNull", "Size"].'
        ),
    ] = None


class MethodNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str,
        Field(description="Format: <fqcn>#<method>(<param-types>). e.g. com.example.UserService#findById(Long)"),
    ]
    kind: Literal["method"]
    name: Annotated[
        str,
        Field(description="Method name. For constructors, matches the class simple name."),
    ]
    return_type: Annotated[
        str,
        Field(
            description="Return type as a string. 'void' for void methods. Constructor return_type is the class FQCN."
        ),
    ]
    parameters: Annotated[
        list[ParameterFact],
        Field(
            description="Method parameters with optional Spring binding metadata (ADR-003 §9 — HTTP arg binding category)."
        ),
    ]
    modifiers: list[Modifier4]
    annotations: Annotated[
        list[str] | None,
        Field(
            description='ALL annotation simple names on this method. e.g. ["GetMapping", "ResponseBody", "Override"].'
        ),
    ] = None
    is_constructor: bool
    line_range: Annotated[list[int], Field(max_length=2, min_length=2)]
    cyclomatic_complexity: Annotated[
        int | None,
        Field(description="McCabe cyclomatic complexity (ADR-004). Null if ClassNode.extraction_mode != 'ast'."),
    ] = None
    cognitive_complexity: Annotated[
        int | None,
        Field(
            description="SonarSource cognitive complexity (ADR-004, Campbell 2018). Null if ClassNode.extraction_mode != 'ast'."
        ),
    ] = None
    method_loc: Annotated[
        int | None,
        Field(
            description="Method lines of code excluding blank lines and comments (ADR-004). Null if ClassNode.extraction_mode != 'ast'."
        ),
    ] = None
    http_metadata: Annotated[
        HttpMetadata | None,
        Field(
            description="HTTP mapping details if this method carries a mapping annotation (@GetMapping etc.). Null/absent if not a request handler."
        ),
    ] = None
    exception_handler: Annotated[
        bool | None,
        Field(description="True if this method carries @ExceptionHandler (ADR-003 §9 — REST exception flow category)."),
    ] = None
    response_status: Annotated[
        int | None,
        Field(
            description="HTTP status code from @ResponseStatus(value=...) or @ResponseStatus(code=...), or null if not present."
        ),
    ] = None
    response_body: Annotated[
        bool | None,
        Field(
            description="True if this method is annotated with @ResponseBody (or is on a @RestController class, which implies it)."
        ),
    ] = None
    is_bean_factory: Annotated[
        bool | None,
        Field(
            description="True if this method carries @Bean (ADR-003 §9 — Boot bootstrap category). Triggers a BeanFactoryEdge from this method to the return type."
        ),
    ] = None


class Node(
    RootModel[
        ModuleNode | ClassNode | InterfaceNode | EnumNode | RecordNode | AnnotationTypeNode | MethodNode | FieldNode
    ]
):
    root: ModuleNode | ClassNode | InterfaceNode | EnumNode | RecordNode | AnnotationTypeNode | MethodNode | FieldNode


class CodeographKnowledgeGraph(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nodes: Annotated[
        list[Node],
        Field(description="All graph nodes. Discriminated by the 'kind' property."),
    ]
    edges: Annotated[
        list[Edge],
        Field(description="All graph edges. Discriminated by the 'kind' property."),
    ]
