# generated by datamodel-codegen:
#   filename:  llm-annotations.schema.json
#   timestamp: 2026-05-06T17:09:08+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class NodeAnnotation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class CodeographLlmAnnotations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    annotations: Annotated[
        dict[str, NodeAnnotation],
        Field(description="Map of node ID → LLM-derived annotation object."),
    ]
