# generated by datamodel-codegen:
#   filename:  manifest.schema.json
#   timestamp: 2026-05-06T15:58:00+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ArtefactMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Relative path from the output directory root.",
            examples=["graph.json", "llm-annotations.json"],
        ),
    ]
    schema_version: Annotated[
        str,
        Field(
            description="Semver of this artefact's own schema at time of production.",
            examples=["1.0.0"],
        ),
    ]
    sha256: Annotated[
        str | None,
        Field(
            description="SHA-256 hex digest of the artefact's canonical bytes. Null only for llm_annotations when --ast-only was used.",
            pattern="^[a-f0-9]{64}$",
        ),
    ]


class Artefacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    graph: Annotated[
        ArtefactMeta,
        Field(
            description="Deterministic AST-derived knowledge graph (out/graph.json)."
        ),
    ]
    llm_annotations: Annotated[
        ArtefactMeta,
        Field(
            description="Non-deterministic LLM enrichment layer (out/llm-annotations.json). sha256 is null when produced with --ast-only."
        ),
    ]


class CodeographRunManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        str,
        Field(
            description="Semver of the manifest schema itself (this file). Bump when manifest structure changes.",
            examples=["1.0.0"],
        ),
    ]
    codeograph_version: Annotated[
        str,
        Field(
            description="Version of the codeograph tool that produced this manifest.",
            examples=["0.1.0"],
        ),
    ]
    artefacts: Annotated[
        Artefacts,
        Field(
            description="Per-artefact metadata keyed by artefact name. Both graph and llm_annotations are always present; llm_annotations sha256 is null when --ast-only was used."
        ),
    ]
