# generated by datamodel-codegen:
#   filename:  manifest.schema.json
#   timestamp: 2026-05-06T17:09:08+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ArtefactMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Relative path from the output directory root.",
            examples=["graph.json", "llm-annotations.json"],
        ),
    ]
    schema_version: Annotated[
        str,
        Field(
            description="Semver of this artefact's own schema at time of production.",
            examples=["1.0.0"],
        ),
    ]
    sha256: Annotated[
        str | None,
        Field(
            description="SHA-256 hex digest of the artefact's canonical bytes. Null only for llm_annotations when --ast-only was used.",
            pattern="^[a-f0-9]{64}$",
        ),
    ]


class Artefacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    graph: Annotated[
        ArtefactMeta,
        Field(description="Deterministic AST-derived knowledge graph (out/graph.json)."),
    ]
    llm_annotations: Annotated[
        ArtefactMeta,
        Field(
            description="Non-deterministic LLM enrichment layer (out/llm-annotations.json). sha256 is null when produced with --ast-only."
        ),
    ]
    scorecards: Annotated[
        dict[str, ArtefactMeta] | None,
        Field(
            default=None,
            description="Eval framework scorecards (added in 1.3.0).",
        ),
    ] = None
    compile_checks: Annotated[
        dict[str, ArtefactMeta] | None,
        Field(
            default=None,
            description="Compile check sidecars per renderer target (added in 1.4.0).",
        ),
    ] = None


class CacheStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    calls: int
    hits: int
    hit_rate: float
    saved_usd_est: float
    incurred_usd_est: float


class CodeographRunManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        str,
        Field(
            description="Semver of the manifest schema itself (this file). Bump when manifest structure changes.",
            examples=["1.5.0"],
        ),
    ]
    codeograph_version: Annotated[
        str,
        Field(
            description="Version of the codeograph tool that produced this manifest.",
            examples=["0.1.0"],
        ),
    ]
    source_path: Annotated[
        str,
        Field(
            description="Absolute path to the input corpus that produced this output. Used by codeograph eval reproducibility check to re-run --ast-only against the same source. Added in manifest schema 1.5.0.",
            examples=["/home/user/projects/my-spring-app"],
        ),
    ]
    corpus_id: Annotated[
        str,
        Field(
            description="Stable identifier for this corpus — the root directory name of the input. Used by codeograph eval golden_graph_agreement check to locate tests/goldens/<corpus_id>/graph.json. Added in manifest schema 1.6.0.",
            examples=["spring-rest-sample", "spring-blog-api"],
        ),
    ]
    artefacts: Annotated[
        Artefacts,
        Field(
            description="Per-artefact metadata keyed by artefact name. Both graph and llm_annotations are always present; llm_annotations sha256 is null when --ast-only was used."
        ),
    ]
    cache_stats: Annotated[
        dict[str, CacheStats] | None,
        Field(
            default=None,
            description="Per-pass LLM cache statistics (added in manifest version 1.1). Keyed by pass name (pass_1, pass_2, pass_3).",
        ),
    ] = None
